/*
 * Build script — chat-widget.js is the single source of truth.
 * Generates:
 *   - dist/chat-widget.min.js   (compact embed script)
 *   - chat-widget.html          (standalone inline <style>+HTML+<script> block)
 *   - chat-widget.min.html      (compact version of the above)
 *
 * Why this exists: earlier in this project's history, the same widget logic
 * was hand-copied into five files, and fixes had to be manually propagated
 * to each one — a real source of drift and bugs. This script removes that
 * risk for three of the five files (the other two, demo/index.html and its
 * own design, are intentionally a separate branded page and stay hand-edited).
 *
 * Usage: node build.js
 */
const fs = require("fs");

const SRC = fs.readFileSync("chat-widget.js", "utf8");

// ---- Extract named top-level pieces from chat-widget.js via brace/paren matching ----

function extractBetween(src, startMarker, endMarker) {
  const start = src.indexOf(startMarker);
  if (start === -1) throw new Error("marker not found: " + startMarker);
  const contentStart = start + startMarker.length;
  const end = src.indexOf(endMarker, contentStart);
  if (end === -1) throw new Error("end marker not found after: " + startMarker);
  return src.slice(contentStart, end);
}

function extractFunctionBody(src, signature) {
  const sigIndex = src.indexOf(signature);
  if (sigIndex === -1) throw new Error("function signature not found: " + signature);
  const braceStart = src.indexOf("{", sigIndex);
  let depth = 0;
  let i = braceStart;
  for (; i < src.length; i++) {
    if (src[i] === "{") depth++;
    else if (src[i] === "}") {
      depth--;
      if (depth === 0) break;
    }
  }
  return src.slice(braceStart + 1, i); // inner body, without the outer braces
}

// CSS_TEXT and MARKUP_TEXT: string-concatenation assignments, extract as-is
const cssAssignment = extractBetween(SRC, "var CSS_TEXT = ", "\n\n  var MARKUP_TEXT");
const markupAssignment = extractBetween(SRC, "var MARKUP_TEXT = ", "\n\n  /**");

// Evaluate the concatenation strings to get real CSS/HTML text
const CSS_TEXT = new Function("return (" + cssAssignment.replace(/;\s*$/, "") + ");")();
const MARKUP_TEXT = new Function("return (" + markupAssignment.replace(/;\s*$/, "") + ");")();

const getFocusableBody = extractFunctionBody(SRC, "function getFocusable(container)");
const initChatBody = extractFunctionBody(SRC, "function initChat(el, formspreeAction)");

// initChat's body starts by destructuring `el` — replace that with direct
// top-level references, since the standalone HTML files don't use the
// root/mount() embed pattern, they reference the IDs directly.
const initChatBodyStandalone = initChatBody.replace(
  'var bubble = el.bubble, win = el.win, body = el.body, closeBtn = el.closeBtn;\n',
  ''
);

// ---- Assemble chat-widget.html ----

const standaloneScript = `<script>
(function () {
  "use strict";

  var REQUEST_TIMEOUT_MS = 15000;
  var FORMSPREE_ACTION = "https://formspree.io/f/xeaokykk"; // ← replace with your own endpoint

  var bubble = document.getElementById("vc-bubble");
  var win = document.getElementById("vc-window");
  var body = document.getElementById("vc-body");
  var closeBtn = document.getElementById("vc-close");
  var formspreeAction = FORMSPREE_ACTION;

  function getFocusable(container) {${getFocusableBody}}
${initChatBodyStandalone}
})();
</script>`;

const htmlDoc = `<!--
  Custom Chat Widget — standalone snippet
  Paste this whole file's contents right before </body> on any page.
  Self-contained: no external CSS, no dependencies, no build step.

  Before using:
  - Replace FORMSPREE_ACTION below with your own endpoint from https://formspree.io
  - Edit the welcome message, header title, and menu option text to match your business

  NOTE: this file is generated by build.js from chat-widget.js (the source
  of truth). Do not hand-edit — edit chat-widget.js and run \`node build.js\`.
-->
<style>${CSS_TEXT}</style>

${MARKUP_TEXT}

${standaloneScript}
`;

fs.writeFileSync("chat-widget.html", htmlDoc);

// ---- Minify helper (shared by dist/chat-widget.min.js and chat-widget.min.html) ----

function compactJs(jsSource) {
  return jsSource
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l !== "" && !l.startsWith("/*") && !l.startsWith("*") && l !== "*/" && !l.startsWith("//"))
    .join("\n");
}

function minifyCss(cssSource) {
  let out = cssSource.replace(/\/\*[\s\S]*?\*\//g, "");
  out = out.replace(/\s+/g, " ").trim();
  out = out.replace(/\s*([{}:;,])\s*/g, "$1");
  out = out.replace(/;}/g, "}");
  out = out.replace(/}/g, "}\n");
  return out.trim();
}

// ---- dist/chat-widget.min.js ----

const minJs = "/*! Custom Chat Widget (compact) — full source: chat-widget.js */\n" + compactJs(SRC) + "\n";
fs.writeFileSync("dist/chat-widget.min.js", minJs);

// ---- chat-widget.min.html ----

const minCss = minifyCss(CSS_TEXT);
const minScriptInner = standaloneScript
  .replace(/^<script>\n/, "")
  .replace(/\n<\/script>$/, "");
const minScript = "<script>\n" + compactJs(minScriptInner) + "\n</script>";

const minHtmlDoc = `<!-- Custom Chat Widget (compact) — paste before </body>. Full commented source: chat-widget.html -->
<style>
${minCss}</style>

${MARKUP_TEXT}

${minScript}
`;

fs.writeFileSync("chat-widget.min.html", minHtmlDoc);

console.log("Built:");
console.log("  dist/chat-widget.min.js  (" + minJs.length + " bytes)");
console.log("  chat-widget.html         (" + htmlDoc.length + " bytes)");
console.log("  chat-widget.min.html     (" + minHtmlDoc.length + " bytes)");
